#' @title Flag dissolved oxygen (DO) sensor noise and potential sonde burial
#' 
#' @description 
#' This function identifies two types of issues with DO sensors:
#' 1. Short-term interference: Flagged when sudden fluctuations occur or DO is 
#' abnormally low.
#' 2. Possible burial: Flagged when persistent interference is detected over a 
#' 24-hour period.
#' The function processes site-parameter dataframes, but only modifies those 
#' containg DO data. For those dataframes without DO data, the function returns
#' the original dataframe unmodified.
#' 
#' @param df A site-parameter dataframe containing water quality parameters with
#' a `flag` column. Must include summary statistics columns (`back1`, `front1`, 
#' `mean`) generated by `generate_summary_statistics()`.
#' 
#' @return A dataframe with the same structure as its input, with additional flags
#' for DO interference and possible burial. 
#' 
#' @examples
#' df <- find_do_noise(df = all_data_summary_stats_list$`riverbluffs-DO`)
find_do_noise <- function(df){
  
  if("DO" %in% df$parameter){
    
    df <- df %>%
      add_flag((back1 - mean >= 0.5 & front1 - mean >= 0.5) | (mean <= 5), "DO interference")
    
    
    # Define a function to check if a given window has any instances of the same word
    check_day_hour_window_fail <- function(x) {
      sum(x) >= 24
    }
    
    df <- df %>%
      data.table::data.table() %>%
      dplyr::mutate(DO_drift_binary = ifelse(grepl("DO interference", flag), 1, 0)) %>%
      dplyr::mutate(right = data.table::frollapply(DO_drift_binary, n = 96, FUN = check_day_hour_window_fail, align = "right", fill = NA),
                    center = data.table::frollapply(DO_drift_binary, n = 96, FUN = check_day_hour_window_fail, align = "center", fill = NA)) %>%
      add_flag(right == 1 | center == 1, "Possible burial")
    
    
    return(df)
    
  } else {
    
    return(df)
    
  }
  
}
